version: '3.4'

services:
  zebrarfidiotconnectorrmclient:
    image: zebrarfidiotconnectorrmclient
    build:
      context: rm-client
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3997:3997
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "index.js"]
