version: '3.4'

services:

  mosquitto:
      image: eclipse-mosquitto:latest
      container_name: mosquitto
      restart: always
      volumes:
        - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:rw
      ports:
        - 1997:1997
      # Shared Network
      networks:
          - mosquitto_go_net
      # Make mosquitto reachable from outside (FX reader)
      hostname: "$host_name"
  angular-app:
    image: 'ng-docker'
    build: './../frontend/'
    ports:
        - 80:80
  rm-middleware:
    image: 'node:lts'
    build: './../rm-client/'
    ports:
        - 3997:3997
networks:
  mosquitto_go_net:
    driver: bridge